export const logs = [
  {
    id: 1,
    userId: 1,
    logName: 'New user',
    logDescription: 'Create new administrator user',
    logSource: 'garosa_dist_dev.user, garosa_dist_dev.user_access',
    logStatus: 1,
    createdOn: '2022-12-16',
    updatedOn: '2022-12-16',
    deleted: 0,
  },
  {
    id: 2,
    userId: 1,
    logName: 'New user',
    logDescription: 'Create new supervisor user',
    logSource: 'garosa_dist_dev.user, garosa_dist_dev.user_access',
    logStatus: 0,
    createdOn: '2022-12-16',
    updatedOn: '2022-12-16',
    deleted: 0,
  },
  {
    id: 3,
    userId: 1,
    logName: 'New user',
    logDescription: 'Create new distributor user',
    logSource: 'garosa_dist_dev.user, garosa_dist_dev.user_access',
    logStatus: 0,
    createdOn: '2022-12-16',
    updatedOn: '2022-12-16',
    deleted: 0,
  },
];
